import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Provides} from "@/components/Provides";
import {Buttons} from "@/components/Buttons";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provides>
        <body className={inter.className}>
            <main className="">
                <Buttons/>
                {children}
            </main>
        </body>
      </Provides>
    </html>
  )
}
